### ISSUE TITLE
Change Heartbeat interval to be in [ms] consistently everywhere: server & all clients

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-heartbeat#6]
Note: I temporary changed hilbert-heartbeat.js for compatibility with HB server and all bash clients (whose pings use [seconds] ATM).

**Comment by malex984** [comment]
@porst17 it may still be that way AFAIR.

**Comment by malex984** [comment]
i have to check

**Comment by porst17** [comment]
5b47a2083e98e1edf4ecfbff01827e1bbfddeadc is the commit that was supposed to be temporary and it should be reverted. Especially, because dividing by `1000` converts `int` to `double` and a floating point number may be written in several different ways, e.g. as decimals or in scientific notation (`100.0` vs `1e2`). The heartbeat server would need to take care of this. And dealing with `int` is way easier anyway.
